import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Card from "~/components/Card";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const listing = api.listings.listingLatestFour.useQuery();

  return (
    <>
      <Head>
        <title>Gimme</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Gim<span className="text-[hsl(280,100%,70%)]">me</span> Shop
          </h1>
          <p className="text-2xl font-medium text-white">
            O que os compradores estão procurando no momento
          </p>
          <div className="grid gap-4 md:grid-cols-3 xl:grid-cols-4">
            {listing.isLoading ? (
              <p>Loading...</p>
            ) : (
              listing.data?.map((item) => {
                return <Card listing={item} key={item.id} />;
              })
            )}
          </div>
          <button className="text-md inline-flex items-center rounded-lg bg-[hsl(280,100%,50%)] px-12 py-4 text-center font-medium hover:bg-[hsl(280,100%,70%)] focus:ring-4 focus:ring-[hsl(280,100%,40%)]">
            <Link href="/listings"> Ver todos </Link>
          </button>
        </div>
      </main>
    </>
  );
};

export default Home;
