import { type NextPage } from "next";
import Head from "next/head";
import Loading from "~/components/Loading";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const messages = api.messages.getMessages.useQuery();

  const messageData = messages.data;
  if (!messageData)
    return (
      <div className="grid h-screen place-items-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <Loading />
      </div>
    );
  return (
    <>
      <Head>
        <title>Ofertas | Gimme</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Suas Ofertas
          </h1>
          <div className="grid place-items-center overflow-auto">
            <div className="relative overflow-x-auto">
              <table className=" w-full  text-left text-sm text-gray-500 dark:text-gray-400">
                <thead className=" bg-gray-700 text-xs uppercase text-gray-400">
                  <tr>
                    <th scope="col" className="px-6 py-3">
                      Item
                    </th>
                    <th scope="col" className="px-6 py-3">
                      Usuário
                    </th>
                    <th scope="col" className="px-6 py-3">
                      Mensagem
                    </th>
                    <th scope="col" className="px-6 py-3">
                      Contato
                    </th>
                  </tr>
                </thead>
                <tbody>
                  {messageData?.map((message) => (
                    <tr key={message.id} className="bg-gray-800">
                      <td className="whitespace-nowrap px-6 py-4">
                        {message.listingName}
                      </td>
                      <td className="whitespace-nowrap px-6 py-4">
                        {message.fromUser?.username}
                      </td>
                      <td className="whitespace-nowrap px-6 py-4">
                        {message.message}
                      </td>
                      <td className="whitespace-nowrap px-6 py-4">
                        {message.fromUser?.email}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
